#!/bin/bash
if [ -f "$HOME/.bash/colors" ]; then
    . "$HOME/.bash/colors"
fi

bash_prompt_command() {
 case $TERM in
 xterm*|rxvt*)
   local TITLEBAR='\[\033]0;\u:${NEW_PWD}\007\]'
    ;;
  *)
   local TITLEBAR=""
    ;;
 esac

 [ $UID -eq "0" ] && UC=$regRed && CC=$regRed && DC=$regRed # root color


 PS1="$TITLEBAR${AC}|${TC}\D{%F %T}${AC}|${UC}\u${AC}@${MC}\h${AC}:[${DC}\w${AC}]${EC} \${?#0}\n${CC}>\[\e]1337;CurrentDir="'$(pwd)\a\]'

 # for terminal line coloring, leaving the rest standard
 none="$(tput sgr0)"
 trap 'echo -ne "${none}"' DEBUG
}
