[general]
live_config_reload = true
working_directory = "None"

# Themes --
import = [
  "~/.config/alacritty/xterm.toml",
  "~/.config/alacritty/keybinds.toml"
]

[window]
title = "Alacritty"
decorations = "none"
blur = true
opacity = 1
padding.x = 8
padding.y = 8

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape= "underline"
blinking = "Always"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
#glyph_offset = { x = 1, y = 0 }
normal.family = "CommitMono Nerd Font Mono"
normal.style = "Regular"
size = 14.0

[font.bold]
family = "CommitMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CommitMono Nerd Font Mono"
style = "Italic"
