#[POOL/DATASET]
#   use_template = standard

[template_standard]
    frequent_period = 15
    frequently = 8
    hourly = 48
    daily = 14
    weekly = 8
    monthly = 6
    yearly = 0
    autosnap = yes
    autoprune = yes
