[tundra/backup]
    use_template = regular
[tundra/data]
    use_template = regular
[tundra/docker]
    use_template = regular
[tundra/home]
    use_template = regular
[tundra/photos]
    use_template = regular
[tundra/srv]
    use_template = regular
[template_regular]
    frequent_period = 15
    frequently = 8
    hourly = 48
    daily = 14
    weekly = 8
    monthly = 12
    yearly = 0
    autosnap = yes
    autoprune = yes
